font_family family='JetBrainsMono Nerd Font'
font_size   16.0

cursor_shape            beam
cursor_shape_unfocused  hollow
cursor_blink_interval   0
cursor_trail            1
mouse_hide_wait         -1

remember_window_size    no
initial_window_width    128c
initial_window_height   32c
window_margin_width     4
hide_window_decorations yes
background_opacity      0.95

copy_on_select      clipboard
clipboard_control   write-clipboard write-primary read-clipboard read-primary

map ctrl+t      new_tab_with_cwd

map shift+enter send_text all \u001b\r

include themes/noctalia.conf
