# hyprlang noerror true
bind = Super, D, overview:toggle
# hyprlang noerror false

plugin:overview {
    autoDrag = false
    exitOnSwitch = true
    workspaceActiveBorder = rgb(bd93f9)
    workspaceBorderSize = 2
}
