#!/usr/bin/env sh


cache_file="${XDG_CACHE_HOME:-$HOME/.cache}/emoji-list.txt"


curl -s https://unicode.org/Public/emoji/latest/emoji-test.txt \
    | grep -v '^#' \
    | grep -v '^$' \
    | grep 'fully-qualified' \
    | awk -F'# ' '{print $2}' \
    | sed -E 's/ E[0-9]+\.[0-9]+ /\t/g' \
    > "$cache_file"
