#!/usr/bin/env sh


cache_file="${XDG_CACHE_HOME:-$HOME/.cache}/emoji-list.txt"


if [ ! -f "$cache_file" ] || [ "$(find "$cache_file" -mmin +43200 -print -quit)" ]; then
    curl -s https://unicode.org/Public/emoji/latest/emoji-test.txt \
        | grep -v '^#' \
        | grep -v '^$' \
        | grep 'fully-qualified' \
        | awk -F'# ' '{print $2}' \
        | sed -E 's/ E[0-9]+\.[0-9]+ /\t/g' \
        > "$cache_file"
fi


cat "$cache_file" | wofi --dmenu --matching=fuzzy --cache-file=/dev/null | awk -F'\t' '{print $1}' | wl-copy
