#!/usr/bin/env bash

PREVIOUS_PERSISTENT=()

handle() {
    case $1 in
        workspacev2*|openwindow*|closewindow*|movewindowv2*)
            
            # 1. Find the highest workspace ID that actually has windows
            max_active_ws=$(hyprctl workspaces -j | jq '[.[] | select(.windows > 0) | .id] | max // 1')
            
            # 2. Target range is from 1 all the way to (max_active_ws + 1)
            limit=$((max_active_ws + 1))
            
            # 3. Build a list of workspaces that SHOULD be persistent right now
            CURRENT_PERSISTENT=()
            for ((i=1; i<=limit; i++)); do
                CURRENT_PERSISTENT+=("$i")
            done
            
            # 4. Clean up workspaces that are no longer in our target range
            for old_ws in "${PREVIOUS_PERSISTENT[@]}"; do
                if [[ ! " ${CURRENT_PERSISTENT[*]} " =~ " ${old_ws} " ]]; then
                    hyprctl keyword workspace "${old_ws},persistent:false" > /dev/null
                fi
            done
            
            # 5. Apply persistence to everything in our current target range
            for new_ws in "${CURRENT_PERSISTENT[@]}"; do
                hyprctl keyword workspace "${new_ws},persistent:true" > /dev/null
            done
            
            # 6. Save the current state for the next event loop
            PREVIOUS_PERSISTENT=("${CURRENT_PERSISTENT[@]}")
        ;;
    esac
}

socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do
    handle "$line"
done
