#!/usr/bin/env bash

active=$(hyprctl activeworkspace -j)

id=$(echo "$active" | jq -r ".id")

name=$(echo "$active" | jq -r ".name")

current=${name#"$id"}
current=${current#-}

new=$(wofi -d -p "Rename workspace:" -Q "$current")

[ $? -ne 0 ] && exit 0

if [ -z "$new" ]; then
    hyprctl dispatch renameworkspace "$id" "$id"
else
    hyprctl dispatch renameworkspace "$id" "$id-$new"
fi
