#!/usr/bin/env bash


cache_file="${XDG_CACHE_HOME:-$HOME/.cache}/emoji-list.txt"


if [ ! -f "$cache_file" ] || [ "$(find "$cache_file" -mmin +43200 -print -quit)" ]; then
    ~/.config/hypr/scripts/clipboard/emoji-fetch
fi


cat "$cache_file" | wofi --dmenu --prompt=emoji --matching=fuzzy --cache-file=/dev/null | awk -F'\t' '{print $1}' | wl-copy
