[accessibility]
ui_scale = 1.25

[audio]
enable_overdrive = true

[bar.default]
border = "primary"
border_width = 2
center = ["clock", "notifications"]
concave_edge_corners = false
end = [
    "audio_visualizer",
    "media",
    "spacer",
    "network",
    "bluetooth",
    "spacer",
    "volume",
    "brightness",
    "spacer",
    "cpu",
    "ram",
    "battery",
    "spacer",
    "session",
]
font_family = "JetBrainsMono Nerd Font"
margin_edge = 8
margin_ends = 8
radius = 8
scale = 1.5
start = ["workspaces", "tray", "active_window"]
thickness = 42

[bar.default.dead_zone.actions]
left = "panel-toggle control-center home"
right = "panel-toggle noctalia/wallhaven:browser"
scroll_down = "workspace-switch next"
scroll_up = "workspace-switch prev"

[brightness]
enable_ddcutil = true
sync_all_monitors = true

[idle]
pre_action_fade_seconds = 30

[idle.behavior.lock]
action = "lock"
enabled = true
timeout = 300

[idle.behavior.screen-off]
action = "screen_off"
enabled = true
timeout = 330

[location]
auto_locate = true

[lockscreen]
blurred_desktop = true

[notification]
position = "top_center"

[plugin_settings."noctalia/kaomoji"]
notify_on_copy = false

[plugins]
enabled = ["noctalia/kaomoji", "noctalia/wallhaven"]

[shell]
polkit_agent = true

[shell.launcher]
categories = false

[shell.screenshot]
directory = "/home/frostbun/Pictures/Screenshots"

[theme]
builtin = "Tokyo-Night"

[theme.templates]
builtin_ids = ["btop", "cava", "hyprland", "kitty"]
community_ids = [
    "opencode",
    "discord",
    "blender",
    "darktable",
    "gimp",
    "vscode",
    "fastfetch",
    "obs",
    "bat",
    "lazygit",
    "yazi",
]

[wallpaper.default]
path = "/home/frostbun/.config/background"

[wallpaper.last]
path = "/home/frostbun/.config/background"

[widget.audio_visualizer]
color_2 = "secondary"

[widget.clock]
format = "{:%a %b %d %I:%M:%S %p}"

[widget.cpu]
visualization = "none"

[widget.media]
hide_when_no_media = true
title_scroll = "on_hover"

[widget.ram]
stat = "ram_pct"
visualization = "none"

[widget.tray]
drawer = true
